### ISSUE TITLE
Any way to add Bobs ores to Start?

### ISSUE THREAD

**Issue by KaneHart** [Oarcinae/FactorioScenarioMultiplayerSpawn#11]
Just wondering if anyone ever modified or added bobs ores to start with. I love to start using his set of mods but not quite sure how I go adding them into the lua.

**Comment by Oarcinae** [comment]
Definitely possible. I stripped out the RSO support for additional ores because there's more overhead and I wanted to keep it simple.

If you are interested in trying, see if you can compare my RSO trimmed code to the current RSO mod. You should see resource configuration for bobs ores and see how that hooks in. Adding it to the starting circle is trivial though.

**Comment by Rsslone** [comment]
I feel like it would be much easier to allow people to set their own resource names. For example I am running Angels, so my starting ores is Saphirite, Stiratite, Rubyte, Bobmonium, Coal.

If you change the values "START_RESOURCE_STONE" to things like "START_RESOURCE_ONE" and add a config value "RESOURCE_ONE_ORE_NAME=stone" to the config.lua so people can easily change the ores if they wanted without going into the separate_spawns.lua. In my setup I just replaced the names of Stone, Copper, Iron, and Uranium.

Or if you wanted to make this Angels and Bobs friendly out of the box you could create a variable for Vanilla, Bobs, and Angels and change the starting ore names based on that. I know for angels ores the ore names are as follows.

Saphirite = angels-ore1
Stiratite = angels-ore3
Rubyte = angels-ore5
Bobmonium = angels-ore6

**Comment by Oarcinae** [comment]
That's a really good idea. I'll change it to a lua table most likely and leave out commented examples for angels/bobs.

**Comment by Rsslone** [comment]
Another note is the oil patches are not crude-oil with angels, its multi phase oil. For simplicity and because oil is not a required resource to start I disabled the oil patches. I think the tile name is "angels-fissure". The only thing you really need is the four listed above plus coal. Bobs I think requires a bit more patches.

**Comment by Oarcinae** [comment]
@Rsslone I pushed a change to try and make the resource configuration more "configurable" :)

Take a look at the new config.lua file and look at OARC_CFG.

Let me know if you have ideas about improving it, and if you can help test the angel/bobs starting resources. I can put those in commented out for easy use later.

**Comment by Rsslone** [comment]
I won't be upgrading until my next server reset but I can do some rough testing with angels / bobs to find the appropriate configuration in a bit. Thanks for adding this, very useful.

**Comment by Oarcinae** [comment]
@Rsslone Let me know if you were able to do any testing on this. Otherwise I'll probably close it as solved since I believe my new implementation should be sufficient.

**Comment by Rsslone** [comment]
Yeah sorry about that, I am still on the OG save and not got around to creating a sandbox to fully test the new version. I'm sure it works but let me throw you the reference to the ore names so players can more easily set it up. Keep in mind for Bobs+Angels you should have Oil patches disabled because Angels uses a different type of patch. Also prob should run the vanilla numbers at least once on default spawn size because I used CHUNK_SIZE*1.8 which I found to be the best.

Ore References
```
########## Vanilla ##########

Iron				= iron-ore
Copper				= copper-ore
Coal				= coal
Stone				= stone


####### Bobs + Angels #######

== Recommended Starting Ores ==

Coal				= coal
Saphirite 			= angels-ore1
Stiratite 			= angels-ore3
Rubyte				= angels-ore5
Bobmonium			= angels-ore6

DISABLE STARTING OIL PATCHES!

== Optional Ores Reference ==

Jivolite 			= angels-ore2
Crotinnium 			= angels-ore4


########## Bobs Ore ##########

== Recommended Starting Ores ==

Iron				= iron-ore
Copper				= copper-ore
Coal				= coal
Stone				= stone
Tin				= tin-ore
Lead (Galena)			= lead-ore

== Optional Ores Reference ==

Bauxite				= bauxite-ore
Cobalt				= cobalt-ore
Gold				= gold-ore
Nickel 				= nickel-ore
Silicon (Quartz)		= quartz
Rutile				= rutile-ore
Silver				= silver-ore
Sulfur				= sulfur
Thorium				= thorium-ore
Tungsten			= tungsten-ore
Zinc				= zinc-ore
```

Config Examples. Your X offsets were hurting my tisms so I changed that in these examples.

```
########## Vanilla ##########
    resource_tiles =
    {
        ["iron-ore"] = 
        {
            amount = 1500,
            size = 12,
            x_offset = -27,
            y_offset = 17
        },
        ["copper-ore"] = 
        {
            amount = 1500,
            size = 12,
            x_offset = -27,
            y_offset = -1
        },
        ["stone"] = 
        {
            amount = 1000,
            size = 12,
            x_offset = -27,
            y_offset = -35
        },
        ["coal"] = 
        {
            amount = 1500,
            size = 12,
            x_offset = -27,
            y_offset = -17
        }
```
```
########## Bobs Mods ##########
    resource_tiles =
    {
        ["iron-ore"] = 
        {
            amount = 1500,
            size = 12,
            x_offset = -27,
            y_offset = 17
        },
        ["copper-ore"] = 
        {
            amount = 1500,
            size = 12,
            x_offset = -27,
            y_offset = -1
        },
        ["stone"] = 
        {
            amount = 1000,
            size = 12,
            x_offset = -27,
            y_offset = -35
        },
        ["coal"] = 
        {
            amount = 1500,
            size = 12,
            x_offset = -27,
            y_offset = -17
        },
        ["tin-ore"] = 
        {
            amount = 1500,
            size = 12,
            x_offset = 17,
            y_offset = -35
        },
        ["lead-ore"] = 
        {
            amount = 1500,
            size = 12,
            x_offset = 17,
            y_offset = -17
        }
```
```
########## Bobs + Angels ##########
    resource_tiles =
    {
        ["angels-ore1"] = 
        {
            amount = 1500,
            size = 12,
            x_offset = -27,
            y_offset = 17
        },
        ["angels-ore3"] = 
        {
            amount = 1500,
            size = 12,
            x_offset = -27,
            y_offset = -1
        },
        ["angels-ore5"] = 
        {
            amount = 1000,
            size = 12,
            x_offset = -27,
            y_offset = -35
        },
        ["coal"] = 
        {
            amount = 1500,
            size = 12,
            x_offset = -27,
            y_offset = -17
        },
        ["angels-ore6"] = 
        {
            amount = 1500,
            size = 12,
            x_offset = 17,
            y_offset = -35
        }
```

**Comment by Oarcinae** [comment]
@Rsslone This is amazing thank you for the work! To keep the example config size reasonable, and because this doesn't get a huge amount of requests I will just leave the resource names in as references and leave it up to the user to configure it themselves. Otherwise it just gets a bit too cluttered.

I'm hoping that will be sufficient for showing people that this could support other resources mods without much trouble.

I will reference this ticket directly in the config file so people can look up your example numbers here.
