### ISSUE TITLE
Loader recipe is set to hidden (factorio game code changed)

### ISSUE THREAD

**Issue by bplein** [Oarcinae/FactorioScenarioMultiplayerSpawn#123]
It looks like with one of the recent 1.1.x releases, Factorio may have neutered the vanilla loaders. They are not available in new OARC games started in the last week or so (and maybe prior). I can enable them via CLI LUA, but they don't show up in the recipes (so you can't hand-build them, nor can you create a factory to create them). Is this something that you could override in LUA? The necessary setting is read-only in game. 

[[1.1.5] Loader recipe is set to hidden](https://forums.factorio.com/viewtopic.php?f=23&t=92808&p=526672)

**Comment by Oarcinae** [comment]
Thanks for the report @bplein! I'll take a look when I get time or if someone helps with a pull request.

**Comment by Oarcinae** [comment]
Thanks for the helpful link! @bplein Since the devs decided to block it, and the lua setting is read only. There is nothing I can do. I'm going to remove it completely at this point since it clearly isn't intended to be supported without mods at this point. Good thing there are lots of mods for good alternatives.

**Comment by bplein** [comment]
Interestingly if you have a BP for loaders you can still make them. But I agree with your thoughts. Let the kids handle this.
