### ISSUE TITLE
Is this project still under maintenance?

### ISSUE THREAD

**Issue by PlexPt** [Oarcinae/FactorioScenarioMultiplayerSpawn#137]

**Comment by PlexPt** [comment]
Then let me maintain it

**Comment by Oarcinae** [comment]
@PlexPt you're welcome to fork or submit changes but I don't plan to hand over this repo to anyone else yet. Are there specific issues you want to resolve or changes you want to make? Lots of others host their own versions already and I have no issues with that.

**Comment by PlexPt** [comment]
Using scenario will have many restrictions, and it is difficult to complete some functions, and the version consistency is not guaranteed, my idea is to make a real MOD and continue to update on mods portal

**Comment by Oarcinae** [comment]
Yeah you're welcome to make a mod from this as long as you make it clear you are the maintainer for it. I ran into several issues a long time ago when trying to make it a mod instead of a scenario, but I'm sure you can figure it out. I have a mod on the portal as well but it just serves this scenario with no other changes.

I have no problems with anyone copying or reusing any of the scenario code however they want, just provide credit somewhere is all I ask. I'll even provide a link to your mod if all goes well with it.

**Comment by Oarcinae** [comment]
Closing this since question was answered.
