### ISSUE TITLE
It's not a lag! Just to say thanks

### ISSUE THREAD

**Issue by IIPoliII** [Oarcinae/FactorioScenarioMultiplayerSpawn#44]
Hey bro,
THANKS for your work
Finish :)
Poli

**Comment by Oarcinae** [comment]
No worries, thank you!

**Comment by IIPoliII** [comment]
Ho and i had a question is it possible that you add a admin menu so you can ban kick? And the admins are wroted in the conifg file of the scenario.
And is there a way to remove old factories of guys? 
Thanks you'are a lord in lua
Poli

**Comment by Cyberzoid1** [comment]
I agree. Thank you for the work on this project

**Comment by Oarcinae** [comment]
@IIPoliII It's a bit hard to write something to remove old factories, there is the "regrowth" option in this scenario but I'm not sure how well it works. For the admin console, I would like to do something but I don't have the time right now. There might be admin mods you can try in the meanwhile?

**Comment by IIPoliII** [comment]
Yeah okay i will watch but is it not possible like when the player come only 5 mins to delete it the same way? Ho and actually i have a problem when i restart my Server it say it that i need to make a new Base. But my "old" base is still there hören can i fix it :)

**Comment by IIPoliII** [comment]
How* sry in m'y phone

**Comment by Oarcinae** [comment]
@IIPoliII Make sure that in your config.lua file, this is enabled and correctly set:
![image](https://user-images.githubusercontent.com/23324249/34910741-bba0cba8-f889-11e7-957b-2b934bd077a6.png)
![image](https://user-images.githubusercontent.com/23324249/34910745-c84806d2-f889-11e7-965d-57f65d50145d.png)

You can adjust that to require that players play for at least X minutes before leaving, otherwise their starting area is cleared. This should be working in the latest version.

**Comment by IIPoliII** [comment]
This wrok of course but for the base removal de can't use the same tactics? And is there a way when i restart the server that when i Spawn Again it goes to my old Base Again and don't promot me to create a new base.
Sorry for m'y english. ;)
