### ISSUE TITLE
Respawn after restart in my base

### ISSUE THREAD

**Issue by IIPoliII** [Oarcinae/FactorioScenarioMultiplayerSpawn#46]
Hello,
I have a problem when i restart my server (for updating and backuping) the map is still the same BUT when i respawn it promot me to create a new base but my old base is still there. How can i fix it that after restart i go in my lastest base again?
Thanks 
Poli

**Comment by Cyberzoid1** [comment]
When you spawn to your new base, are you using the spawn control to set your respawn location?

**Comment by IIPoliII** [comment]
Wich Spawn control @Cyberzoid1 ?the only problem is thats when i restart my server (with saving) it promot me like i am a new player but my "old base" is still there. 
Thanks for your help
Poli

**Comment by Cyberzoid1** [comment]
Does this happen when you disconnect from the game then reenter. Without restarting the server?

**Comment by IIPoliII** [comment]
No without restarting it works (but every night i restart for backuping :).

**Comment by Oarcinae** [comment]
@IIPoliII  I'm not sure I understand how to reproduce this, can you provide more info?

- Is this a linux dedicated server?
- How are you stopping the server? Ctrl-C? /save? /quit?
- How are you resuming the game?
- What do you mean you restart for backup? To backup the PC? or the save game or something else?
- Are you running the latest 0.16.16?

I am able to stop my dedicate linux server by using ctrl-c. The game saves automatically. I then can later resume the game and I never have any issues like you are describing.

The spawn control is this: http://prntscr.com/i0rj5p
It allows you to set a new respawn point so that if you die, you can change where you want to respawn. That should not have any effect if you are restarting the game or resuming a saved game though.

**Comment by IIPoliII** [comment]
Hello,
1) So yes it's a dedicated (self-hosted)
2) My server is stoped by the script of lgsm he make first /save and then crtl+c
3) I start my server with --start-server-load-latest (the first time i created him with --start-server-load-scenario)
4) i use the lgsm script too it makes a perfect copy of the server in a .zip file
5) Yes i am running always the lastest experimental game (that why i restart it checks on the website too)

It's wired that it work by your side :(.

**Comment by IIPoliII** [comment]
Okay i founded the issue if you start the server you conncect like 1 minute (normally there is a map clean up) and you restart the server before the map cleanup then when the server will restart you are like a new player
My fault
Sorry.
Poli

**Comment by IIPoliII** [comment]
Ho and what is the little other button you have i am intersted :)

**Comment by Oarcinae** [comment]
Ah, no problem. Yes, if you want to change the minimum time you must play, you can adjust this number in the config:
![image](https://user-images.githubusercontent.com/23324249/34956749-7e949d1e-f9f8-11e7-8413-4ebea091ce4f.png)
![image](https://user-images.githubusercontent.com/23324249/34956758-881ccd7a-f9f8-11e7-9aba-af417062a70b.png)

The first one is default true, which enables the automatic removal of player bases who start the game and leave immediately. The second one is the number of minutes you must play first to make sure your base doesn't get deleted. This makes it so if you host a public server, if a lot of people join and leave, you won't have a lot of empty bases taking up the map.

Which button? The small blueprint one is a mod for upgrading blueprints.

**Comment by IIPoliII** [comment]
oh okay thanks the button is not a scenrio :'(

**Comment by Oarcinae** [comment]
https://mods.factorio.com/mods/Klonan/upgrade-planner

If you have any other questions or issues, feel free to open a new issue or reply to the 0.16 general issues thread. Will close this one now.
