### ISSUE TITLE
Angel's Refining support

### ISSUE THREAD

**Issue by Fishqt** [Oarcinae/FactorioScenarioMultiplayerSpawn#51]
This is an amazing scenario for when I want to play with my friends, so amazing that it's basically essential for us now.

However, we're trying to widen our mod usage to include Angel's mods, which seems to cause some troubles with generating the map because Angel's Refining replaces iron and copper.

Is there a way to add support for it? Can I do it myself?

Thanks!

**Comment by Oarcinae** [comment]
Hi, I haven't been very active in awhile so I apologize for the slow response!

If you want to try adding it yourself, I think the correct place would be in `function GenerateStartingResources(surface, pos)`. This is in the oarc_utils.lua file, around line 1064.

Let me know if you have any success.

I plan on updating my scenario once 0.17 is released since I expect there be a LOT of required changes.

**Comment by Fishqt** [comment]
No problem! 

I went through all the files of the scenario and I successfully made a nice working startzone with all the required modded resources. Your code is very well commented so it was a much easier task than I originally thought! 

Looking forward to 0.17 and what direction your scenario goes!
