### ISSUE TITLE
Scenario functionality broke after some patch but..

### ISSUE THREAD

**Issue by davv1** [Oarcinae/FactorioScenarioMultiplayerSpawn#97]
but I'm not sure after which patch, or which mod breaks it. I'm still using scenario which was made few months ago, and today after return(last version we played was 0.17.23 iirc) some functionalities don't work, and they are:

* shared chat(we need to /s like on PvP scenario)
* all buttons on top panel(only OARC related)

I will extend list as I find more functionalities not working.

Also, I found one "dummy" player entity after one startup, but I just ignored it.

Requesting previous saves is impossible, as we use factorio.zone service, which doesn't allows for autosave-history or something like that. I can only get current logs, or current save from their server for now.

**Comment by Oarcinae** [comment]
Hmmm, this is new. I've not seen those kind of failures before. I would definitely suggest restarting fresh if possible when things fail like that.

The dummy char was a bug in the game for one of the versions.

For shared to break, some major things would have to break.

I definitely suggest updating to the latest scenario code just so I know I'm not chasing down old issues.

Let me know if you can reproduce the issue, or have logs or specific crashes.

**Comment by davv1** [comment]
Everything was working fine before update, but after I updated to [f076835](https://github.com/Oarcinae/FactorioScenarioMultiplayerSpawn/commit/f0768358e697840047b8681e0878ab8d7a5087b2), this happened upon loading save:


![obraz](https://user-images.githubusercontent.com/13569795/57829908-c71c9780-77b0-11e9-937f-1903cb9e88a0.png)

[factorio-current.log](https://github.com/Oarcinae/FactorioScenarioMultiplayerSpawn/files/3185594/factorio-current.log)

Here's save before updating to mentioned commit: [click](https://drive.google.com/file/d/1CStZFeFVGNKeNH_7W9eKPqSukW9sudQ1/view?usp=sharing)
And save after updating: [click](https://drive.google.com/file/d/1CStZFeFVGNKeNH_7W9eKPqSukW9sudQ1/view?usp=sharing)

**Comment by Oarcinae** [comment]
@davv1 If you're trying to migrate saves, you'll have a bad time since there's a lot of stuff that will break. Either stick with the same scenario code for the whole run, or start a new one. With the experimental versions of factorio and my scenario still in work, I can't guarantee no breaking changes.

**Comment by davv1** [comment]
Last time it worked perfectly @Oarcinae when you was adding buttons to restart player data.

**Comment by Oarcinae** [comment]
I'm not saying it won't work sometimes, but it's something I can't help with because there are just some breaking changes that can't be migrated. Like the one you just posted about can't be fixed. I suggest using an older commit or older save and do not update the scenario code unless you're restarting the map.

**Comment by davv1** [comment]
Oki.
